sudo: required
language: go

services:
- docker

env:
  global:
  # Quay user
  - secure: BoiN+g4PxJJoaenaX9NKYB9YU2Y+JizfD07PrFrq7yYyjyd7UHSM1Ak2mE7qsj4Tq+napcpJb5QjT60VUvESh3dPxW8iED/+CWQlCUSJXjcad6R9fJvkgpmru3ZoMIg7ZvJnq07HUjdVIjvHqu/XzaRcGK2nCkCymh6vWw9machnIADNWAtlXQNTK8Fq/7y19MaVrHSPfjk4Lq8c9VXpv6gX838jBmcI0x3j3xtSz9K6hKL2znbXGJdyC82BckMGlVX3gDg6djIIQma5BLvJ73LMMTILsFxjQkOjKZYMF0hdobQqAmAHmssYQw/3Zicse/WS1peRsQV3QUm/VJz9eC8F4+hIKJaObVa7l0nVmjMGE+tke4L3IM6mdupOXQm4dyxRH5Oa3BKa6B2u1GypmNUQB/vsN26VykXOgLMXG6+VoIDc4kksL3nqojIopot1MjOkl0tQjg55YXGqOTgJgkgI/JLRSE7GLz/G7uJP1Ob2+qXrlnDO0tpeZuiTY8mV7eWdoYraT7BXp5fb0Ay+r3rPq96Hd+bGW/Ur9HbrJnw8r3hbgx5T7ypS3fYLTKlBXW4pAo35b85U5cBPrwFe5bcRJ3e4MbGrMmejiCVgHb2W5ZhZKXnqNiVRHbexWnQGKF7qkgYmfwHXcT0r491vnG0g+cBIlJYaYwt9mnXqW7Q=
  # Quay pass
  - secure: fMNIKrAG9MNqCQBXR3Uk9xgM4fS1oyZynzka/JGxKdNHngot322Rpd7qmVnCVp1bQHbNdQL+xHCQTIOFaNgnYnMI4YsPHm0JnOHrC0wNqaFhaLve1lA/2OgKid+XZqI0Lf4zmrWZZe2FnWpFkXSGC3v6aJikBl3+zIQ5b50DS3rieOeLhuBQZbem5OqT0dxbgH+g+zHM6CSH8MlcLVUX71Ukb8cwzO8//aUyyjhGIZam9qGXqbai0smNL3tlI7iRMLvYgaT7K49WsxUse7DjSdLPZfuIf9Nad2bW4763ftW9iNelFhOB4T9519/gMBmOvCVRdr3f9R3DhO5z3RwcvDyJi46IKZrSLD1+I40dc7/NSQHR0aY7UDquSETxJvIZDfPpMAo/0DrVtypHTGO6auDuH4Qh1KrlFbJrE7hqmokELbsZtdMK1l6r5z3LTxeDx5++gu9VGBVm1Ujmr7Ivl3vukKt7DVEyUYAK+KvAC1sP6ac3ppUbg2PBvLpzK3Lkbu4EULYq7H8JGw8vjRT8HO4dxyJWepiQ4KQFpnRw9SgpB9rDe63lkiyqA5A7+KeHJdIED32A+Zge4vz5FlRkX+MKXoSXGR2eH8LTVq48dTTSih9UQLrm085AdUemofzBO+RyFdDEDbjJOaOw6FZ4G7+awCWH9QE7bVdmtQ++0iA=
script:
- make all
