sudo: required
language: go

env:
  global:
  # Quay user
  - secure: NFAMNjQhJNYg0FIGzTP+n7VSmspUFq28AhUrdZdA810BTEkf/ACjXhnx7tuqME2ni/uDKGjSiFeA8td2OddBS3T9S27bSkFSGdE84gxq7dV9VqnONr813fLrpx/a7bbxs/2u4oPJERSYwGR7ZIH4or7bWOmzUHeFPZDfcJLuXgM+jG65WofoPfVM/fyyJDvir8in2IhdLEGnyXfFtSSJklB58HCRV82wYTEiU9ovrl2rM8fRDJ1nbW/kmd7sAmCJn/JVDVODSgig+NG/1RVwFcSrCzTL9DvZf6T1DUPVNuvpSUHNK5elJ0u2qoAC0PbnVDvE+4j+50Ad1Wm56RKiBoOuhWhfb4P4FE+2rRTz3xTJXPnbe6LvtDPLo6/5l0O/fsPVlLK/yUdH+BhNB2v6xjgdFNrKj6WGUGvjCzn0B+ibwmmRIfKblbwr8Hp5iWFjtSPZOm9a0a93bHtdlBwRI9jSXH/IQbThRTDWFaPgvkUsqo0F1SmBAnRkOCH4WLIaMEJl7C2LIVmNjfk1S/pQhN9+J/sJrwWZfWU2M5lTryj2D162MtPPogrPHpHjEgqrYtghZAyRha4zDNwcOcD3pNL6ncQ6VBjX8MuJJEqrvU47Q12XaxVlIeLKp/gMPFoi7U3+w743W8Jq4fPVNAW4O7jgsphNpvFy7Qh/YLQHoMU=
  # Quay pass
  - secure: hfYwJMjimDeQJBJUl/6rQ+m/sNx9NVmnb23Jl8wCVyWW5ZjCuL35TPETj23bOju6ckpSWkSvuIIiJdo9RYFyNneBwDZzJlk78ViNxtMO7vP8xcg4w0Qw5tB8oevUyrZui4PQBwWl9/8cEvooQrCP5YAoJJJVD6iHxH8wM0NJdgnbK4QbQIQR65ElbqpGBgOkvqeGivMQMe45ds2IugTN3WgIirq+t2rQAa06Nr1m9Tsq6b3g+Z1o5t67+Lk25GFZ5GjDXXeQBnJh4nq1EGe/iJDur80jPU4hYTMHbemBjxU7WdvixqMX+TCrqJUiVP2w4bzpqKP66QlAOgNIVU6nDfQdxmAell9bs/GQuSpf1hoMtIhz/qQpR8sYhuSFuCu0lF86cgoXh6kKSuuIUdG2kdlMFIEHhZqK9jyfUzWHk9kwFr8K9oODBH1Sabbr1lHLw4AaY0HijqUPNFkzq92eYmaZ4jUy7pSajMizn6aToYFulNq56lKxY4HyFKf+iZXZYLAxmfYoeppR7qBtQ/y+jYqLrtysDp97cSLvhxPQaiPxF5jFcNZnht4PrVsxOR/9fC4NpprFgYqbGAeHzyKC+o3L57ppRleT+L6EFV7ZAL2T/ZWqeNMt3nMO9V0AgsdgkAJsIO7qUnAo/DJYx0r5OKH/WbMqX0nt3RkcbJzNKv4=
  matrix:
  - KUBERNETES_VERSION=latest
  - KUBERNETES_VERSION=stable

script:
- make -e init docker-build docker-images

deploy:
  provider: script
  script:
  - make -e docker-push
  on:
    tags: true