---
kind: PodSecurityPolicy
apiVersion: extensions/v1beta1
metadata:
  name: privileged
spec:
  privileged: true
  allowPrivilegeEscalation: true
  hostNetwork: true
  hostPID: true
  hostIPC: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPorts:
  - min: 1
    max: 65536

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-security-policy-privileged-ergaleia
  namespace: toolbox
  labels:
    name: ergaleia
subjects:
- kind: ServiceAccount
  namespace: toolbox
  name: ergaleia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user